
local material=Material()
material.Effect = game:LoadEffect("shader/Character.fx")
material.ParameterMap:SetVector("g_MaterialAmbientColor", Vector4(0.3,0.3,0.3,1.0))
material.ParameterMap:SetVector("g_MaterialDiffuseColor", Vector4(1.0,1.0,1.0,1.0))
material.ParameterMap:SetTexture("g_MeshTexture", game:LoadTexture("texture/casual19_m_35.jpg"))
material.ParameterMap:SetTexture("g_NormalTexture", game:LoadTexture("texture/casual19_m_35_normal.png"))
material.ParameterMap:SetTexture("g_SpecularTexture", game:LoadTexture("texture/casual19_m_35_spec.png"))
material.ParameterMap:SetTexture("g_CubeTexture", game:LoadCubeTexture("texture/galileo_cross.dds"))
game:InsertMaterial("casual19_m_highpolyPhong", material)