#define DIRECTINPUT_VERSION 0x0800
#define NOMINMAX
//Find all "#include <", Match case, Whole word, Subfolders, Keep modified files open, Find Results 1, "Current Project", "*.c;*.cpp;*.cxx;*.cc;*.tli;*.tlh;*.h;*.hpp;*.hxx;*.hh;*.inl;*.rc;*.resx;*.idl;*.asm;*.inc"
#include <windows.h>
#include <string>
#include <string>
#include <sstream>
#include <boost/function.hpp>
#include <boost/tuple/tuple.hpp>
#include <boost/utility/enable_if.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/type_traits/is_void.hpp>
#include <boost/type_traits/is_same.hpp>
#include <limits>
#include <boost/static_assert.hpp>
extern "C" {
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
}
#include <vector>
#include <atlbase.h>
#include <d3d9.h>
#include <d3dx9.h>
#include <atlbase.h>
#include <boost/shared_ptr.hpp>
#include <deque>
#include <string>
#include <tchar.h>
#include <Windows.h>
#include <boost/shared_ptr.hpp>
#include <boost/unordered_map.hpp>
#include <vector>
#include <boost/shared_ptr.hpp>
#include <dinput.h>
#include <atlbase.h>
#include <d3dx9math.h>
#include <vector>
#include <atlbase.h>
#include <boost/shared_ptr.hpp>
#include <boost/shared_ptr.hpp>
#include <list>
#include <vector>
#include <unzip.h>
#include <boost/weak_ptr.hpp>
#include <boost/unordered_map.hpp>
#include <boost/scoped_ptr.hpp>
#include <Windows.h>
#include <vector>
#include <boost/unordered_map.hpp>
#include <boost/unordered_set.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/shared_ptr.hpp>
#include <WTypes.h>
#include <Mmsystem.h>
#include <dsound.h>
#include <boost/shared_ptr.hpp>
#include <vector>
#include <boost/shared_ptr.hpp>
#include <d3d9.h>
#include <d3dx9tex.h>
#include <atlbase.h>
#include <atltypes.h>
#include <Windows.h>
#include <atlbase.h>
#include <atlwin.h>
#include <atltypes.h>
#include <string>
#include <boost/shared_ptr.hpp>
#include <boost/function.hpp>
#include <boost/weak_ptr.hpp>
#include <set>
#include <map>
#include <d3d9.h>
#include <string>
#include <assert.h>
#include <Windows.h>
#include <assert.h>
#include <math.h>
#include <msctf.h>
#include <malloc.h>
#include <strsafe.h>
#include <sstream>
#include <d3d9.h>
#include <dinput.h>
#include <dsound.h>
#include <tchar.h>
#include <ft2build.h>
#include <crtdbg.h>
#include <strstream>
  //Matching lines: 84    Matching files: 28    Total files searched: 49
