
emitter=SphericalEmitter()
emitter.SpawnInterval=1/100
emitter.ParticleLifeTime=10
emitter.SpawnSpeed=5
emitter.SpawnInclination.Value=math.rad(45)
local Azimuth=math.rad(360)*8
emitter.SpawnAzimuth:AddNode(0,0,Azimuth/10,Azimuth/10)
emitter.SpawnAzimuth:AddNode(10,Azimuth,Azimuth/10,Azimuth/10)
emitter.ParticleColorA:AddNode(0,255,0,0)
emitter.ParticleColorA:AddNode(10,0,0,0)
emitter.ParticleColorR:AddNode(0,255,0,0)
emitter.ParticleColorR:AddNode(10,0,0,0)
emitter.ParticleColorG:AddNode(0,255,0,0)
emitter.ParticleColorG:AddNode(10,0,0,0)
emitter.ParticleColorB:AddNode(0,255,0,0)
emitter.ParticleColorB:AddNode(10,0,0,0)
emitter.ParticleSizeX:AddNode(0,1,0,0)
emitter.ParticleSizeX:AddNode(10,10,0,0)
emitter.ParticleSizeY:AddNode(0,1,0,0)
emitter.ParticleSizeY:AddNode(10,10,0,0)
emitter.Texture=game:LoadTexture("texture/flare.dds")
game:SaveEmitter("emitter_01.txt", emitter)

material=Material()
material.DiffuseTexture=game:LoadTexture("texture/casual19_m_35.jpg")
material.NormalTexture=game:LoadTexture("texture/casual19_m_35_normal.png")
material.SpecularTexture=game:LoadTexture("texture/casual19_m_35_spec.png")
game:SaveMaterial("material/casual19_m_highpolyPhong.txt", material)

-- material=Material()
-- material.Effect=game:LoadEffect("shader/SimpleSample.fx", EffectMacroPairList())
-- material:SetVector("g_MaterialAmbientColor",Vector4(0.1,0.1,0.1,0.1))
-- material:SetVector("g_MaterialDiffuseColor",Vector4(1.0,1.0,1.0,1.0))
-- material:SetTexture("g_MeshTexture",game:LoadTexture("texture/Checker.bmp"))
-- game:SaveMaterial("material/lambert1.txt", material)

-- material=Material()
-- material.Effect=game:LoadEffect("shader/WaterEffect.fx", EffectMacroPairList())
-- material:SetTexture("g_WaterNormalTexture",game:LoadTexture("texture/WaterNormal2.png"))
-- material:SetTexture("g_CubeTexture",game:LoadTexture("texture/galileo_cross.dds"))
-- game:SaveMaterial("material/waterPhong.txt", material)

-- material=Material()
-- material.Effect=game:LoadEffect("shader/ApexEffect.fx", EffectMacroPairList())
-- material:SetVector("g_MaterialAmbientColor",Vector4(0.1,0.1,0.1,0.1))
-- material:SetVector("g_MaterialDiffuseColor",Vector4(1.0,1.0,1.0,1.0))
-- material:SetTexture("g_MeshTexture",game:LoadTexture("texture/TileWall.dds"))
-- game:SaveMaterial("brick.txt", material)

-- material=Material()
-- material.Effect=game:LoadEffect("shader/ApexEffect.fx", EffectMacroPairList())
-- material:SetVector("g_MaterialAmbientColor",Vector4(0.1,0.1,0.1,0.1))
-- material:SetVector("g_MaterialDiffuseColor",Vector4(1.0,1.0,1.0,1.0))
-- material:SetTexture("g_MeshTexture",game:LoadTexture("texture/Plaster_Tileable.dds"))
-- game:SaveMaterial("stone.txt", material)